// ── Enemy domain types ──────────────────────────────────────────────────────

export enum EnemyId {
  Wolf = "wolf",
  Swordsman = "swordsman",
  Shieldbearer = "shieldbearer",
  HighlandArcher = "highlandArcher",
  Pikeman = "pikeman",
  Berserker = "berserker",
  WarHoundHandler = "warHoundHandler",
}

/** Identifies which AI strategy module drives this enemy's behaviour. */
export type EnemyBehaviorType =
  | "wolf"
  | "swordsman"
  | "shieldbearer"
  | "highlandArcher"
  | "pikeman"
  | "berserker"
  | "warHoundHandler";

/** Named animation keys for an enemy entity's spritesheet. */
export interface EnemyAnimationSet {
  idle: string;
  walk: string;
  attack: string;
  hurt: string;
  death: string;
  /** Block animation — only present for shield-bearing enemies. */
  block?: string;
}

/** Static definition of an enemy type — lives in data files, never mutated. */
export interface EnemyDefinition {
  id: EnemyId;
  name: string;
  baseHp: number;
  baseDamage: number;
  /** Attack reach in pixels at 1920×1080 design resolution. */
  range: number;
  behavior: EnemyBehaviorType;
  animations: EnemyAnimationSet;
  /** Currency awarded to the player when this enemy is defeated. */
  lootValue: number;
}

/**
 * A scheduled enemy encounter within a chapter run.
 * Generated by the level generator; consumed by the run machine.
 */
export interface EnemyEncounter {
  enemyId: EnemyId;
  /** 0–100: position along the chapter's total traversal distance. */
  positionPercent: number;
  isBoss: boolean;
}
