// Core game logic — barrel export
export * from "./types/hero";
export * from "./types/run";
export * from "./types/save";
export * from "./types/chapter";
export * from "./types/enemy";
export * from "./types/upgrade";
export * from "./types/combat";
export * from "./machines/gameMachine";
export * from "./machines/traversalMachine";
export * from "./machines/duelMachine";
export * from "./systems/timer";
export * from "./systems/combat";
export * from "./systems/health";
export * from "./systems/economy";
export * from "./systems/progression";
export * from "./systems/levelGenerator";
export type { ObstacleType, ObstacleInstance } from "./entities/obstacles/obstacleBase";
export { OBSTACLE_COLLISION_RADIUS } from "./entities/obstacles/obstacleBase";
export type { IEnemyBehavior, EnemyAction } from "./entities/enemies/enemyBase";
export { wolfBehavior } from "./entities/enemies/wolf";
